name: Send Message to Slack Channel
on:
  push:
    branches:
      - main-copy
    paths:
      - 'README.md'
jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Send Message to Slack Channel
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "Read Me file was updated https://github.com/${{github.repository}}/pull/${{github.event.number}}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
